/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_emilianoagurcia;

import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emili
 */
public class Examen2P2_EmilianoAgurcia extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Examen2P2_EmilianoAgurcia() {
        initComponents();
        Cargar();
        Actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TF_Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SP_Edad = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        SP_Reparados = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        CB_Empleados = new javax.swing.JComboBox<>();
        BT_EliminarEmpleado = new javax.swing.JButton();
        BT_AgregarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SP_Costo = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        TF_Modelo = new javax.swing.JTextField();
        CB_Marca = new javax.swing.JComboBox<>();
        SP_Year = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CB_Estado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Mod_SP_Costo = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        Mod_TF_Modelo = new javax.swing.JTextField();
        Mod_CB_Marca = new javax.swing.JComboBox<>();
        Mod_SP_Year = new javax.swing.JSpinner();
        Mod_CB_Estado = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        CB_CarroModificar = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        BT_AgregarCarro = new javax.swing.JButton();
        BT_ModificarCarro = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TB_ListaCarros = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Reaparaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(TF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 260, 30));

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 20));

        SP_Edad.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 1));
        jPanel1.add(SP_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, -1));

        jLabel2.setText("Edad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        SP_Reparados.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel1.add(SP_Reparados, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 100, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Eliminar Empleado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 60, 650, -1));

        jLabel4.setText("Num. de Identidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));
        jPanel1.add(TF_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 260, 30));

        jLabel5.setText("Carros Reparados");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 10, 760));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agregar Empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 660, -1));

        jPanel1.add(CB_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 330, 30));

        BT_EliminarEmpleado.setText("Eliminar");
        BT_EliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EliminarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(BT_EliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 200, 40));

        BT_AgregarEmpleado.setText("Agregar");
        BT_AgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AgregarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(BT_AgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 200, 40));

        jTabbedPane1.addTab("CRUD Empleados", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Marca");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel8.setText("Modelo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel9.setText("Año de fabricación");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        SP_Costo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        jPanel2.add(SP_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 190, 30));

        jLabel10.setText("Estado de Reparación");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));
        jPanel2.add(TF_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 290, 30));

        CB_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nissan", "Toyota", "Kia", "McLaren", "Suzuki", "Honda", "Ferrari" }));
        jPanel2.add(CB_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, 30));

        SP_Year.setModel(new javax.swing.SpinnerNumberModel(1800, 1800, 2023, 1));
        jPanel2.add(SP_Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 190, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 10, 760));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Modificar Carro");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 60, 490, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Lista de Carros");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 400, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Crear Carro");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 410, -1));

        CB_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. En espera de entrar a reparación", "2. En reparación", "3. En espera de pago de reparación", "4. Saldo pagado", "5. En espera de ser entregado", "6. Entregado" }));
        CB_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_EstadoActionPerformed(evt);
            }
        });
        jPanel2.add(CB_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 290, 30));

        jLabel14.setText("Costo de Reparación");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel15.setText("Marca");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jLabel16.setText("Modelo");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        jLabel17.setText("Año de fabricación");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));
        jPanel2.add(Mod_SP_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 190, 30));

        jLabel18.setText("Estado de Reparación");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));
        jPanel2.add(Mod_TF_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 290, 30));

        Mod_CB_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nissan", "Toyota", "Kia", "McLaren", "Suzuki", "Honda", "Ferrari" }));
        jPanel2.add(Mod_CB_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 190, 30));
        jPanel2.add(Mod_SP_Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 190, 30));

        Mod_CB_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. En espera de entrar a reparación", "2. En reparación", "3. En espera de pago de reparación", "4. Saldo pagado", "5. En espera de ser entregado", "6. Entregado" }));
        Mod_CB_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mod_CB_EstadoActionPerformed(evt);
            }
        });
        jPanel2.add(Mod_CB_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 290, 30));

        jLabel19.setText("Costo de Reparación");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        jPanel2.add(CB_CarroModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 200, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Carro a Modificar");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, 20));

        BT_AgregarCarro.setText("Agregar");
        BT_AgregarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AgregarCarroActionPerformed(evt);
            }
        });
        jPanel2.add(BT_AgregarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 200, 40));

        BT_ModificarCarro.setText("Modificar");
        BT_ModificarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ModificarCarroActionPerformed(evt);
            }
        });
        jPanel2.add(BT_ModificarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, 200, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 10, 760));

        jScrollPane2.setBorder(null);

        TB_ListaCarros.setBackground(new java.awt.Color(51, 51, 51));
        TB_ListaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Fabricado en", "Estado", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_ListaCarros.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(TB_ListaCarros);
        if (TB_ListaCarros.getColumnModel().getColumnCount() > 0) {
            TB_ListaCarros.getColumnModel().getColumn(0).setResizable(false);
            TB_ListaCarros.getColumnModel().getColumn(1).setResizable(false);
            TB_ListaCarros.getColumnModel().getColumn(2).setResizable(false);
            TB_ListaCarros.getColumnModel().getColumn(3).setResizable(false);
            TB_ListaCarros.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 400, 660));

        jTabbedPane1.addTab("CRUD Carros", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Simulación", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Pagos", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Entregas", jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TB_Reaparaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Empleado", "Carro a Reparar", "Exito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_Reaparaciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TB_Reaparaciones.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(TB_Reaparaciones);
        if (TB_Reaparaciones.getColumnModel().getColumnCount() > 0) {
            TB_Reaparaciones.getColumnModel().getColumn(0).setResizable(false);
            TB_Reaparaciones.getColumnModel().getColumn(1).setResizable(false);
            TB_Reaparaciones.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 780, 520));

        jTabbedPane1.addTab("Reparaciones", jPanel6);

        Background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_EstadoActionPerformed

    private void Mod_CB_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mod_CB_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mod_CB_EstadoActionPerformed

    private void BT_AgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AgregarEmpleadoActionPerformed
        if(TF_Nombre.getText().isBlank() || TF_ID.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Por favor complete la información");
        }else{
            try {
                Empleado newEmpleado = new Empleado(
                        TF_Nombre.getText(),
                        (int) SP_Edad.getValue(),
                        TF_ID.getText(),
                        (int) SP_Reparados.getValue()
                );
                ListaEmpleados.add(newEmpleado);
                Actualizar();
                
                JOptionPane.showMessageDialog(this, "Creado Exitosamente");
                Limpiar_AgregarEmpleado();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_BT_AgregarEmpleadoActionPerformed

    private void BT_EliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EliminarEmpleadoActionPerformed
        if(CB_Empleados.getSelectedIndex() != -1){
            try {
                Empleado Selected_Empleado = (Empleado) CB_Empleados.getSelectedItem();
                ListaEmpleados.remove(  ListaEmpleados.indexOf(Selected_Empleado));
                Actualizar();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
        }
    }//GEN-LAST:event_BT_EliminarEmpleadoActionPerformed

    private void BT_AgregarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AgregarCarroActionPerformed
        if(CB_Marca.getSelectedIndex() == -1 || TF_Modelo.getText().isBlank() || CB_Estado.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Por favor complete la información");
        }else{
            Carro newCarro = new Carro(
                    (String) CB_Marca.getSelectedItem(),
                    TF_Modelo.getText(),
                    (int) SP_Year.getValue(),
                    (String) CB_Estado.getSelectedItem(),
                    (double)SP_Costo.getValue()
            );
            ListaCarros.add(newCarro);
            Actualizar();
            
            JOptionPane.showMessageDialog(this, "Creado Exitosamente");
            Limpiar_AgregarCarro();
        }
    }//GEN-LAST:event_BT_AgregarCarroActionPerformed

    private void BT_ModificarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ModificarCarroActionPerformed
        if(CB_CarroModificar.getSelectedIndex() != -1){
             Carro Selected_Carro = (Carro) CB_CarroModificar.getSelectedItem();
        }
    }//GEN-LAST:event_BT_ModificarCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen2P2_EmilianoAgurcia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_AgregarCarro;
    private javax.swing.JButton BT_AgregarEmpleado;
    private javax.swing.JButton BT_EliminarEmpleado;
    private javax.swing.JButton BT_ModificarCarro;
    private javax.swing.JPanel Background;
    private javax.swing.JComboBox<String> CB_CarroModificar;
    private javax.swing.JComboBox<String> CB_Empleados;
    private javax.swing.JComboBox<String> CB_Estado;
    private javax.swing.JComboBox<String> CB_Marca;
    private javax.swing.JComboBox<String> Mod_CB_Estado;
    private javax.swing.JComboBox<String> Mod_CB_Marca;
    private javax.swing.JSpinner Mod_SP_Costo;
    private javax.swing.JSpinner Mod_SP_Year;
    private javax.swing.JTextField Mod_TF_Modelo;
    private javax.swing.JSpinner SP_Costo;
    private javax.swing.JSpinner SP_Edad;
    private javax.swing.JSpinner SP_Reparados;
    private javax.swing.JSpinner SP_Year;
    private javax.swing.JTable TB_ListaCarros;
    private javax.swing.JTable TB_Reaparaciones;
    private javax.swing.JTextField TF_ID;
    private javax.swing.JTextField TF_Modelo;
    private javax.swing.JTextField TF_Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    //Para modificar desde el Main y darle set a la lista en el Binario
    ArrayList <Empleado> ListaEmpleados = new ArrayList();
    ArrayList <Carro> ListaCarros = new ArrayList();
    
    private void Cargar(){
        try {
            //Empleados
            adminArchivos AE = new adminArchivos("./Empleados.emi");
            AE.DownloadEmpleados();
            for (Empleado emp : AE.getListaEmpleados()) {
                ListaEmpleados.add(emp);
            }             
            
            //Carros
            adminArchivos AC = new adminArchivos("./Carros.emi");
            AC.DownloadCarros();
            for (Carro carro : AC.getListaCarros()) {
                ListaCarros.add(carro);
            }
        } catch (Exception e) {
        }
    }
    private void Actualizar(){
        try {
        //ListaEmpleados
            adminArchivos AE = new adminArchivos("./Empleados.emi");
            AE.DownloadEmpleados();
            AE.setListaEmpleados(ListaEmpleados);
            AE.UploadEmpleados();
            
        //ListaCarros
            adminArchivos AC = new adminArchivos("./Carros.emi");
            AC.DownloadCarros();
            AC.setListaCarros(ListaCarros);
            AC.UploadCarros();
        
        //Eliminar Empleado
            //ComboBox
            DefaultComboBoxModel mCB_Empleados = (DefaultComboBoxModel) CB_Empleados.getModel();
            mCB_Empleados.removeAllElements();
            for (Empleado empleado : ListaEmpleados) {
                mCB_Empleados.addElement(empleado);
            }
            CB_Empleados.setModel(mCB_Empleados);
            
        //Modificar Carro
            //ComboBox
            DefaultComboBoxModel mCBCB_CarroModificar = (DefaultComboBoxModel) CB_CarroModificar.getModel();
            mCBCB_CarroModificar.removeAllElements();
            for (Carro carro : ListaCarros) {
                mCBCB_CarroModificar.addElement(carro);
            }
            CB_CarroModificar.setModel(mCBCB_CarroModificar);
            
            //Casillas / Datos
            if(CB_CarroModificar.getSelectedIndex() != -1){
                Carro Selected_Carro = (Carro) CB_CarroModificar.getSelectedItem();
                
                Mod_CB_Marca.setSelectedItem( Selected_Carro.getMarca() );
                Mod_TF_Modelo.setText(Selected_Carro.getModelo());
                Mod_SP_Year.setValue( Selected_Carro.getYearFabricado() );
                Mod_SP_Costo.setValue( Selected_Carro.getCosto() );
                Mod_CB_Estado.setSelectedItem( Selected_Carro.getEstado() );
            }
            
        //Listar Carros    
            DefaultTableModel mTB = (DefaultTableModel) TB_ListaCarros.getModel();
            mTB.setRowCount(0);
            for (Carro carro : ListaCarros) {
                Object[] newRow = {
                    carro.getMarca(),
                    carro.getModelo(),
                    carro.getYearFabricado(),
                    carro.getEstado(),
                    carro.getCosto()
                };
                mTB.addRow(newRow);
            }
            TB_ListaCarros.setModel(mTB);
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void Limpiar_AgregarEmpleado(){
        TF_Nombre.setText("");
        SP_Edad.setValue(10);
        SP_Reparados.setValue(0);
        TF_ID.setText("");
    }
    private void Limpiar_AgregarCarro(){
        CB_Marca.setSelectedIndex(0);
        TF_Modelo.setText("");
        SP_Year.setValue(1800);
        SP_Costo.setValue(0);
        CB_Estado.setSelectedIndex(0);
    }

}
